export const CompetencesSuggestion = [
    { title: "Html"},
    { title: "Css"},
    { title: "JavaScript"},
    { title: "React.js"},
    { title: "Node.js"},
    { title: "MongoDB"},
    { title: "Mongoose"},
    { title: "Bootsrap"},
    { title: "Matérial-Ui"},
    { title: "Antd"},
    { title: "Vue.js"},
    { title: "jQuery"},
    { title: "SQL"},
    { title: "Php"},
    { title: "Laravel"},
    { title: "Symfony"},
    { title: "mySQL"},
    { title: "React Native"},
    { title: "Flutter"},
    { title: "Ionic"},
    { title: "Titanium"},
    { title: "Wordpress"},
    { title: "WooCommerce"},
    { title: "Shopify"},
    { title: "Next.js"},
    { title: "Npm"},
    { title: "Yarn"},
    { title: "Sass"},
    { title: "Scss"},
    { title: "Styled Components"},
    { title: "Adobe Photoshop"},
    { title: "Adobe InDesign"},
    { title: "Adobe Illustrator"},
    { title: "Adobe XD"},
    { title: "Adobe After Effect"},
    { title: "Adobe Premiere"},
    { title: "Adobe Lightroom"},
    { title: "SketchUp"},
    { title: "Dimension"},
    { title: "Dust3D"},
    { title: "FreeCAD"},
    { title: "Facebook"},
    { title: "Instagram"},
    { title: "Snapchat"},
    { title: "GraphQL"},
    { title: "Redux"},
    { title: "Google Analytics"},
    { title: "SEO"},
    { title: "Traduction Français-Anglais"},
    { title: "Traduction Anglais-Français"},
    { title: "Traduction Français-Arabe"},
    { title: "Traduction Arabe-Français"},
    { title: "Traduction Arabe-Anglais"},
    { title: "Traduction Anglais-Arabe"},
    { title: "Traduction Français-Allemand"},
    { title: "Traduction Allemand-Français"},
    { title: "Microsoft Word"},
    { title: "Microsoft Excel"},
    { title: "Microsoft PowerPoint"},
    { title: "Emailing"},
    { title: "Portrait"},
    { title: "Publish"},
    { title: "Dark "},
    { title: "Ubersuggest"},
    { title: "Active Campaign "},
    { title: "Buzzsumo"},
    { title: "SEMrush"},
    { title: "Subscribers"},
    { title: "Canva"},
    { title: "LeadPages"},
    { title: "Hellobar"},
    { title: "Git"},
    { title: "GitHub"},
    { title: "PhpMyAdmin"},
    { title: "Strapi"},
    { title: "Expres.js"},
    { title: "Three.js"},
    { title: "Particles.js"},
    { title: "Figma"},
];
